title: Nathaniel K. Green
description: My personal website detailing my interests and hobbies.
remote_theme: just-the-docs/just-the-docs

url: https://nathaniel-k-green.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - "jekyll-github-metadata"
