title: Nathaniel K. Green
description: My personal website detailing my interests and hobbies.
remote_theme: just-the-docs/just-the-docs

url: https://nathaniel-k-green.github.io

aux_links:
  Template Repository: https://github.com/nathaniel-k-green.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
